remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
# github:
#   zip_url: http://example.com/download.zip
#   another_url: another value
title: [Grant Ensign Portfolio]
description: [Portfolio of Grant Ensign, a Data Analyst]